### ISSUE TITLE
Option to select private key from keystore using alias

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#172]
If keystore has multiple private keys then we should have an option to select which private key to use. If you can provide this feature to select private key using alias, it would be helpful(Please refer TLSUtils.java which was shared over email for some help  on this).

**Comment by RichardHightower** [comment]
Please attach the TLSUtils.java. Thank you!

**Comment by gstaware** [comment]
I am unable to attach TLSUtils.java here but I remember I sent you as a attachment in one of the recent email. Please check else I will send it once again. Thanks.

**Comment by RichardHightower** [comment]
I believe this is done already.

**Comment by gstaware** [comment]
Do we need to add any parameter in nats-bridge.yaml config file for this?

**Comment by RichardHightower** [comment]
Unless you configured a matching channel on the queue manager with the corresponding cipher spec (not the same cipher suite that was specified by the client, permutations are in the link below) and have the queue manager configured with a certificate issues from the root/sub ca it won't work.  We can test it out in our env and let you know if we encounter any issues, however applicable commands are below….
To configure the queue manager:
Issue runmqsc <qmgr name> from cli then
ALTER QMGR SSLKEYR('/var/mqm/qmgrs/QM1/ssl/MyKey')
(to change the location of the kdb file which contains the full chain for the cert, root/sub ca and cert, no concept of separate keystore and truststore for the queue manager)
then configure the channel with something like this….
DEFINE CHANNEL(C1.TO.QM1) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCIPH(TLS_RSA_WITH_AES_128_CBC_SHA)
SSLCAUTH(REQUIRED) DESCR('Receiver channel using TLS from C1 to QM1')
C1.TO.QM1 will be the channel you specify in the embedded MQ client and the matching cipher suite for this would either be SSL_RSA_WITH_AES_128_CBC_SHA or TLS_RSA_WITH_AES_128_CBC_SHA depending on whether you were using an IBM or Oracle JRE (permutations are below).  If you are using the Oracle JCE you'll also need to pass this….. java -Dcom.ibm.mq.cfg.useIBMCipherMappings=false
Most of the doc can be found here…
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q113220_.htm
https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.sec.doc/q012660_.htm
If you run into issues be sure and capture the linked exceptions which will give the actual MQ error code which is in the 2000’s (2035, 2085, 2058) otherwise you'll just get some generic error.
5:07
ignore that for now.. but later let’s talk
5:07
this too
5:07
To set them within the application, use the code below. The location of the trustStore and the keyStore can point to the same file:
System.setProperty("javax.net.ssl.trustStore","<location of trustStore>");
System.setProperty("javax.net.ssl.keyStore","<location of keyStore>");
System.setProperty("javax.net.ssl.keyStorePassword","<password>");
To use the the -D flag:
java  -Djavax.net.ssl.trustStore=<location of trustStore>
         -Djavax.net.ssl.keyStore=<location of keyStore>
         -Djavax.net.ssl.keyStorePassword=<password><app>
