### ISSUE TITLE
As we discussed, please run benchmarks once code is stabilized and share the results.  

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#178]
As we discussed, please run benchmarks once code is stabilized and share the results.  If you develop some utility to run these benchmarks, kindly share the same with us so that we can also use the same to run benchmarks in mastercard environment.

**Comment by RichardHightower** [comment]
We have perf tests that test just the bridge and nats connection and use a fake JMS bridge.
This test exceeds 10K request/response per second with a single worker well above the SLA. 
The speed issue will not be with NATS or the NATS bridge. 
It will be when using a JMS server or IBM MQ and will depend on how the server/JMS cluster is set up and tuned. 

The trick to scale when using JMS / IBM MQ will be the number of workers and tasks to run at one time. 

We do not have an IBM MQ cluster of servers to do perf tests with nor the expertise to set up a large IBM MQ cluster per se. 

We could do a large load test with an ActiveMQ cluster (due to licenses and expertise), but the reality is that the NATs bridge and NATs are not the long pole. The long pole will be the JMS or IBM MQ set up.

**Comment by ColinSullivan1** [comment]
I'm of the mindset that benchmark results from any vendor have an implicit bias and rarely reflect real world conditions. When benchmark code and infrastructure is transparent, it's better, but still warrants investigation.

So, we highly suggest users running end to end benchmarks in their own environments.  Throughput and latency varies drastically based on compute and network resources, # of clients, physical topology, and application design.  Our numbers would not reflect your environment, so we're hesitant to share a public benchmark beyond something simple (which generates a vanity metric and is useful for defining theoretical limits, but rarely applies to the real world).

If you run benchmarks in your environment and are able to share the results would benefit the ecosystem greatly!

**Comment by gstaware** [comment]
Agreed Colin that it would produce correct results in our environments. Would it be possible for you guys to develop some utility that can be used in our environment to run benchmarks? Also if you have some examples for the same it would be very helpful for us.
